---
title: "p8105_hw3_jl7035"
author: "Jeffrey Lin"
date: "2024-10-12"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Load Necessary Libraries 

```{r}
library(tidyverse)
library(ggplot2)
library(ggridges)
```
## Problem 1
```{r}

```


## Problem 2

Load in and clean each dataset
```{r}
demographic_df <- 
  read_csv("Data/nhanes_covar.csv",
    na = c("", "NA", "."),
    skip = 4
  ) %>% 
  janitor::clean_names() %>% 
  mutate(
    sex = factor(
      sex, 
      levels = c("1", "2"), 
      labels = c("male", "female")),
    education = factor(
      education,
      levels = c("1", "2", "3"),
      labels = c("Less than high school", "High School Equivalent", 
                 "More than high school")
    )
  ) %>% 
  filter(
    age >= 21
  ) %>% 
  drop_na()
  
head(demographic_df)
  
accelerometer_df <- 
  read_csv("Data/nhanes_accel.csv",
    na = c("NA", "", ".")
  ) %>%  
  janitor::clean_names() %>%
  pivot_longer(
    min1:min1440,
    names_to = "Minute",
    values_to = "MIMS"
  ) %>% 
  mutate(
    Minute = str_remove(Minute, "min")
  )
  

```
Join dfs together
```{r}
accel_participant_df <-
  left_join(
    demographic_df, 
    accelerometer_df, 
    by = "seqn")

anti_join(demographic_df, accel_participant_df)
anti_join(accelerometer_df, accel_participant_df)

```


Produce reader-friendly table for number of men and women in each education
category
```{r}
demographic_df %>% 
  group_by(sex, education) %>% 
  count() %>% 
  knitr::kable()

```
Looking at the count of the number of men and women in each education category,
we can see that

create visualization of age distribution for each education category
```{r}
ggplot(demographic_df, aes(x = education, y = age, fill = sex)) +
  geom_boxplot(outliers = TRUE)

```



## Problem 3
```{r}

```

